name: CI/CD

on: push

jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: auth
      name: Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    - id: deploy
      name: Deploy
      uses: google-github-actions/deploy-cloud-functions@v2
      with:
        name: 'accommodation-scrapper'
        runtime: 'python39'
        entry_point: 'handler'
        memory_mb: '128'
        region: 'europe-west2'
        timeout: '60'
        min_instances: '0'
        max_instances: '1'
        env_vars:
            "BUCKET=${{ secrets.BUCKET }},\
            BOT_TOKEN=${{ secrets.BOT_TOKEN }},\
            CHAT_ID=${{ secrets.CHAT_ID }},\
            ACCOMMODATION_LOGIN=${{ secrets.ACCOMMODATION_LOGIN }},\
            ACCOMMODATION_PASSWORD=${{ secrets.ACCOMMODATION_PASSWORD }}"

