name: CI/CD

on: push

jobs:
  deploy:
    name: Deploy to Yandex Cloud
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Cloud Function
        uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.OAUTH_TOKEN }}
          function_id: 'd4ef3fel1s14vja0fn3k'
          runtime: 'python39'
          memory: '128'
          execution_timeout: '15'
          entrypoint: 'main.handler'
          environment:
            "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }},\
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }},\
            BUCKET=${{ secrets.BUCKET }},\
            BOT_TOKEN=${{ secrets.BOT_TOKEN }},\
            CHAT_ID=${{ secrets.CHAT_ID }},\
            ACCOMMODATION_LOGIN=${{ secrets.ACCOMMODATION_LOGIN }},\
            ACCOMMODATION_PASSWORD=${{ secrets.ACCOMMODATION_PASSWORD }}"
          source: '.'
          exclude: 'README.md,.git,.github'
